version: '3.4'

services:
  
  streamer.web:
    build:
      context: ./web-player
    environment:
      RUNTIME_STREAMER_API_URL: 'api'
      API_PROXY: 'true'
    ports:
      - "80:80"
    depends_on:
      - streamer.api

  streamer.api:
    image: ${DOCKER_REGISTRY-}streamerapi
    build:
      context: ./Streamer.API
    ports:
      - "8080:80"
    volumes:
      - mediadata:/app/media
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      DATABASE_CONNECTIONSTRING: 'Server=database;Database=postgres;Port=5432;User Id=postgres;Password=docker;'
    depends_on:
      - database.upgrade

  database.upgrade:
    build:
      context: ./DatabaseUpgrade
    environment:
      DATABASE_CONNECTIONSTRING: 'Server=database;Database=postgres;Port=5432;User Id=postgres;Password=docker;'
    command: ["sh", "./wait-for.sh", "--timeout=60", "database:5432", "--", "dotnet", "DatabaseUpgrade.dll"]
    depends_on:
      - database

  database:
    restart: always
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

volumes:
  dbdata:
  mediadata:
