version: '3.4'

services:

  streamer.web:
    build:
      context: ./WebPlayer/web-player
    ports:
      - "80:80"

  streamer.api:
    image: ${DOCKER_REGISTRY-}streamerapi
    build:
      context: ./Streamer.API
    ports:
      - "8080:80"
    volumes:
      - mediadata:/app/media
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      DATABASE_CONNECTIONSTRING: 'Server=database;Database=postgres;Port=5432;User Id=postgres;Password=docker;'
    depends_on:
      - database
      
  database:
    restart: always
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

volumes:
  dbdata:
    external: true
  mediadata:
    external: true
