version: '3.4'

services:
  streamer.api:
    image: ${DOCKER_REGISTRY-}streamerapi
    ports:
      - "8080:80"
    build:
      context: ./Streamer.API
      dockerfile: ./Dockerfile
    environment:
      DATABASE_CONNECTIONSTRING: 'Server=database;Database=postgres;Port=5432;User Id=postgres;Password=docker;'
  database:
    restart: always
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

volumes:
  dbdata:
    external: true
